### ISSUE TITLE
inplace operators are slooooow

### ISSUE THREAD

**Issue by Tim---** [AlexAltea/htypes#8]
Hi !

I am trying to use your module to play with a Feistel cipher and noticed that at each iteration, the code gets slower. 
I figured that using inplace operators was the problem.

I came up with a minimal example showing the difference between inplace and "normal" operators:

This code is getting slower after a few iterations:
```
from nativetypes import *
x = uint32(1)
while True:
    print(x)
    x *= x
```

Replacing the inplace operator gets a significant speed improvement:

```
from nativetypes import *
x = uint32(1)
while True:
    print(x)
    x = x * x
```

From what I understand, this happens because the following code assumes that the op result is an integer, where it is in fact another nint object. This leads to nested nint objects that slow down the operations.

https://github.com/AlexAltea/ntypes/blob/27cf3aa76457a5890092bc347775d7f1bd982eee/nativetypes/native_int.py#L102-L105

**Comment by AlexAltea** [comment]
Nice catch! Thanks for debugging this issue, and apologies for the late reply. I completely forgot about it.

This issue is now fixed as of https://github.com/AlexAltea/ntypes/commit/967259266aeb3a3dc15fccfbcddceba960ba85cc

(Sometimes the output of `op()` is indeed an `int`, so the `isinstance` call is unavoidable, but it should be cheap).

You gan grab the fix in the latest release `v1.0.7` at https://pypi.org/project/nativetypes/.
